name: mapos_app
description: "Sistema de gerenciamento DigiOS"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.15
  http: ^1.2.0
  flutter_boxicons: ^3.1.0
  table_calendar: ^3.0.0
  intl: ^0.19.0
  animated_bottom_navigation_bar: ^1.3.3
  intro_slider: ^3.0.1
  url_launcher: ^6.3.0
  page_transition: ^2.1.0
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  flutter_masked_text2: ^0.9.1
  provider: ^6.1.2
  flutter_html: ^3.0.0-beta.2
  flutter_localization: ^0.3.2
  photo_view: ^0.15.0
  flutter_downloader: ^1.11.7
  flutter_local_notifications: ^19.1.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.0.11
  device_info_plus: ^11.4.0
  fluttertoast: ^8.2.4
  flutter_typeahead: ^5.2.0
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  web: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
